### ISSUE TITLE
[Bug]: Held note sprites teleport below the screen in downscroll

### ISSUE THREAD

**Issue by Oculuseyeball** [Turbine-Software/FNFSharp#10]
### Platform

Windows

### What happened?

hold notes are chipping through the input buttons or something, idk why, it's ugly and gross and it make me angry
![unknown (1)](https://user-images.githubusercontent.com/106492964/180302191-d2c42a32-15aa-4da4-b7c3-9d762263d99a.png)
![unknown (2)](https://user-images.githubusercontent.com/106492964/180302249-fa14a5f9-4836-47a2-8fe7-87b5a5ce5e3f.png)
![unknown (3)](https://user-images.githubusercontent.com/106492964/180302293-d01fdcc3-5169-4c35-8db5-d1c77466d3a8.png)

### Steps to reproduce

you just play the game like normal

### Version

ver 1.4.0

**Comment by thepercentageguy** [comment]
fixed. ( https://github.com/Turbine-Software/FNFSharp/commit/f8ad5972ccf867da3503cbe3366f2bda48a3ea4d )
